### ISSUE TITLE
DeltE calculation formula

### ISSUE THREAD

**Issue by Pjcaogthb** [DIDSR/cpr#4]
Hi WC,

Could you share the equation to calculate Delta E? I used the Matlab function deltaE(I1,I2,'isInputLab',true), didn't get the same results as your application.

Thanks.
PJ

**Comment by WeiChungCheng** [comment]
Hi @Pjcaogthb,

Please notice that in Matlab, [deltaE()](https://www.mathworks.com/help/images/ref/imcolordiff.html) calculates CIE 1976 ΔE, while [imcolordiff()](https://www.mathworks.com/help/images/ref/imcolordiff.html) calculates ΔE 94 or CIEDE2000. The CIEDE2000 is used in this app except for two boxplots.

Thanks,
WC
