### ISSUE TITLE
Cannot open UFT-8 with BOM

### ISSUE THREAD

**Issue by sksg** [DIDSR/cpr#5]
The program fails with an input file that uses UTF-8 with *Byte-Order-Mark* (BOM). See https://en.wikipedia.org/wiki/Byte_order_mark for info on BOM.

If converting the same file to UTF-8 without BOM, the program works.

Please note that Excel will export csv files with BOM.

FYI, you can use VScode to quickly check or change the encoding, including the usage of BOM.

**Comment by WeiChungCheng** [comment]
Thanks for the useful comments. We will include a remark about the input requirement in the next release.

**Comment by sksg** [comment]
No worries! Happy to help.

I hope you will reconsider making it work for UFT8 files with BOM. All Microsoft products (like Excel) consider the BOM mandatory, and so you are effectively making it difficult for people using Microsoft product to use your tool. I suggest taking a look at something like this:
https://se.mathworks.com/matlabcentral/fileexchange/75708-update-bom-for-unicode-text-files

Otherwise, please include a warning in the documentation, in particular for using this tool together with Excel. Also please consider adding a note for a workaround using, for example, VS code to remove the BOM.

Alternatively, if you can consider open sourcing the code and allow contributions, then I can make a pull request for you. 

BR, Søren

**Comment by WeiChungCheng** [comment]
Hi Søren,

We are evaluating your suggestions. In the next release, the GUI and source code will be included. Thank you for your input!

WCC

**Comment by WeiChungCheng** [comment]
Hi Søren, @sksg,

The GUI and source code have been added to branch V2. Please take a look and advise how the BOM problem should be addressed. Thanks!

WCC

**Comment by sksg** [comment]
> Hi Søren, @sksg,
> 
> The GUI and source code have been added to branch V2. Please take a look and advise how the BOM problem should be addressed. Thanks!
> 
> WCC

Hi WCC

Thanks for publishing some of the code! I really appreciate that.

As for helping out, I am not sure I am able in the published code. Maybe I am missing something obvious, but I cannot find the code reading in the data from a txt file. I tried searching the repo for an `fread` or an `fopen` and did not find anything.

I am guessing that the `fread` is actually called in the `.exe` code, and the resulting DeviceData object is then passed to the CPR object. Is the `.exe` code published anywhere?

BR, Søren

**Comment by WeiChungCheng** [comment]
Hi Søren, @sksg,

Thanks for checking the code. I just added the GUI app `cprapp.mlapp`, which was incidentally deleted. Find `readmatrix()` in line #232.

WCC

**Comment by sksg** [comment]
I see. Thank you.

Since I do not have a Matlab license right now, I cannot really edit `.mlapp` files that easily. I tried a workaround with octave, but it does not support the `readmatrix()` function. So, I cannot fix it until I get Matlab again. I usually use Matlab a couple of times a year, so I can have a look next time I get hold of a license.

I was surprised to learn that `readmatrix()` supports Excel files out of the box (according to docs). I would think that `readmatrix()` is supposed to support UTF-8 files with BOM, so that might be an issue that Matlab will fix themselves. When I get access to Matlab again, I will try and see how `readmatrix()` works with UTF-8 files with BOM and report the error if it does not work.

If anyone else has the time and Matlab access, please feel free to move ahead without me.

**Comment by WeiChungCheng** [comment]
Hi Søren, @sksg,

Thanks again for checking the code. Could you provide some sample Excel files for me to reproduce the BOM problem? We can then proceed from there.

WCC

**Comment by sksg** [comment]
[XYZ_WithBOM.csv](https://github.com/DIDSR/cpr/files/13649137/XYZ_WithBOM.csv)
[XYZ_WithoutBOM.csv](https://github.com/DIDSR/cpr/files/13649138/XYZ_WithoutBOM.csv)

I hope these files will do the job. Let me know if they behave as expected.

**Comment by WeiChungCheng** [comment]
Hi Søren, @sksg,

The GUI `cprapp.mlapp` seems working with both `XYZ_WithBOM.csv` and `XYZ_WithoutBOM.csv`. Here is the screenshot:

![XYZ_WithBOM_screenshot](https://github.com/DIDSR/cpr/assets/83293961/3d7a1846-7d76-42ea-8ad4-64fd4f7894d2)

WCC

**Comment by sksg** [comment]
Hi WCC.

I can confirm that I can use the `cprapp.exe` together with UFT8-with-BOM files. I also just reconfirmed that the old (v1) `XYZ_1pager.exe` from the `main` branch still does not work with UTF8-with-BOM files. So it seems there is an update between the two apps that fixed the issue.

In that case, the issue appears to be fixed in v2 `cprapp.exe`.
