### ISSUE TITLE
Cannot launch XYZ_1pager.exe

### ISSUE THREAD

**Issue by hermanmiis** [DIDSR/cpr#6]
I launch it and the image "splash.png" show awhile.
But the "exe" crash immediately.
Is it possibile we could get the  .m file?

**Comment by WeiChungCheng** [comment]
Hello @hermanmiis,

The "XYZ_1pager.exe" needs to run in the command mode with two parameters. Please try the following:

• Enter DOS command mode
• \cd \Users\xxx\Downloads\cpr\one_pager
• XYZ_1pager.exe XYZ_Reference.csv XYZ_Subject.csv

Specify the working directory on your computer. Replace <XYZ_Reference.csv> and <XYZ_Subject.csv> with your own testing data. Besides the Matlab Runtime, Matlab basic and the toolboxes are not required to run this app. Please let us know if you have additional questions and suggestions.

Thanks,
WC
