### ISSUE TITLE
Color Performance Review Tool for Endoscopy Devices

### ISSUE THREAD

**Issue by zql0512** [DIDSR/cpr#7]
Hello, may I ask a question？
I have already installed Matlab Runtime 9.12 (Version 9.12 tested) 、Matlab (Version 9.12 tested)、mage Processing Toolbox (Version 11.5 tested) 、Computer Vision Toolbox (Version 9.12 tested) 、Statistics and Machine Learning Toolbox (Version 12.3 tested)，Why am I still unable to open the XYZ_1pager ？

**Comment by WeiChungCheng** [comment]
Hello @zql0512,

Sorry for the confusion. This topic has been discussed in https://github.com/DIDSR/cpr/issues/6. Please try the following:

The "XYZ_1pager.exe" needs to run in the command mode with two parameters:

• Enter DOS command mode
• \cd \Users\xxx\Downloads\cpr\one_pager
• XYZ_1pager.exe XYZ_Reference.csv XYZ_Subject.csv

Specify the working directory on your computer. Replace <XYZ_Reference.csv> and <XYZ_Subject.csv> with your own testing data. Besides the Matlab Runtime, Matlab basic and the toolboxes are not required to run this app.

Please let me know if you have additional questions and suggestions.

Thanks,
WC
