### ISSUE TITLE
Error: CTF archive is invalid

### ISSUE THREAD

**Issue by ntclancy** [DIDSR/cpr#8]
Hi,

I have installed Matlab Runtime 9.12 and tried running the program from the command prompt using "one_pager.exe XYZ_Reference.csv XYZ_Subject.csv".

The splash screen appears immediately followed by an error message "CTF archive invalid".

I also have Matlab R2023b installed. Am I missing a step?

**Comment by WeiChungCheng** [comment]
Please try V2 and let us know if you encounter the same problem.

**Comment by ntclancy** [comment]
Thank you very much for the quick reply. I don't have the same problem but instead have a different one:
When running the exe I get an error 'the program...cannot start or run due to incompatibility with 64-bit versions of Windows'.

However, I am able to run the app successfully from Matlab AppDesigner.

**Comment by WeiChungCheng** [comment]
Hello @ntclancy,

Thanks for the update. If you still want to run the compiled executable, you will need to install MATLAB Runtime R2023a to run V2.

Thanks,
WC
